### ISSUE TITLE
zk_STARK_Validator proof verification fails "Total sum and non-negative constraint validation failed"

### ISSUE THREAD

**Issue by monperrus** [okx/proof-of-reserves#33]
I'm verifying the proofs.

Actions:

- cloned this repo
- downloaded `por_904793965_proof_data.zip` (sha256: 61334cbd1c8c2ebda9324675da3902a6e814e95fcdcf40d48201d68c57da4312)
- downloaded user proof
- run `python ./zk_STARK/zk_STARK_Validator.py`

after verify batch proofs: `success = True`
after verify trunk proofs: `success = False`

```
============ Validation started ==============
Total sum and non-negative constraint validation failed
============ Validation finished =============
```

What's the root cause? How to fix this?

**Comment by Jason-LI2020** [comment]
I downloaded the por_904793965_proof_data.zip and user proof and the test passed.

```
============ Validation started ==============
Total sum and non-negative constraint validation passed
Inclusion constraint validation passed
============ Validation finished =============
```
I'm wondering why your log didn't show the inclusion constraint verification part. 

Could you show me your working space structure list?

Is it "mtree_root": "ce83183dacd4f840762142c874917c9f3105ed6873e0d00fc26562ebf0f1144a" in your sum_proof_data/truck/sum_proof.json ?

And could you try with the executable program zk_STARK/zk_STARK_Validator ?

**Comment by monperrus** [comment]
Making progress, thanks @Jason-LI2020 

> Is it "mtree_root": "ce83183dacd4f840762142c874917c9f3105ed6873e0d00fc26562ebf0f1144a" in your sum_proof_data/trunk/sum_proof.json ?

yes

With the released [zk_STARK_Validator_linux_amd64_v3.0.1.zip](https://github.com/okx/proof-of-reserves/releases/download/v3.0.6/zk_STARK_Validator_linux_amd64_v3.0.1.zip), it completes.

With the checkout of master (c2aefa7eea38aa5ca3adcdd604b290bde16aa7d4), it fails.
 
What's the difference between the release and the python file in this repo?

**Comment by Jason-LI2020** [comment]
They should be the same, and I tested with the python file and it completed.

If it could be verified successfully with the executable program, then the proof data you dowloaded should be correct.

So I guess most probably the problem is about the location of the files.

Have you figured out why your log didn't show the inclusion constraint verification part?

Did you put the sum_proof_data, inclusion_proof.json and the zk_STARK_Validator.py at the same direction/location? Could you show me your working space structure?

**Comment by monperrus** [comment]
Problem fixed, thanks! I can now run it.

The problems were:

- zk_STARK_Validator.py considers folder `sum_proof_data` in the folder where it resides, not in the current working directory (and I was calling `python ./zk_STARK/zk_STARK_Validator.py`)
- the Github repo [folder](https://github.com/okx/proof-of-reserves/tree/main/zk_STARK) already contains a folder `sum_proof_data`, so   zk_STARK_Validator.py did not complain about the absence of `sum_proof_data`. I suggest to remove `sum_proof_data` from the repo.

Why is `zk_STARK_Validator` implemented in Python and not in Go? (it would be so much faster)

**Comment by Jason-LI2020** [comment]
That's great!
Yes we are considering a next version with rust.

**Comment by monperrus** [comment]
great! thanks again for the support. I'll publish a write-up of my experience to verify 
proof-of-reserves of different exchanges.

**Comment by Jason-LI2020** [comment]
Yeah it's a great work. And maybe if users could follow the instruction there would be no problem of verification.
https://www.okx.com/help/zero-knowledge-proofs-what-are-zk-starks-and-how-do-they-work

![image](https://github.com/okx/proof-of-reserves/assets/73786353/0f20d97b-dc28-4af7-a59e-35fbd8574022)

**Comment by monperrus** [comment]
FYI, there are a few broken/outdated links on this page, incl. 
https://github.com/okx/proof-of-reserves/releases/tag/v2.0.0 which should be be 
https://github.com/okx/proof-of-reserves/releases/tag/v3.0.0 or perhaps simply 
https://github.com/okx/proof-of-reserves/releases/.

**Comment by monperrus** [comment]
thanks a lot for your help @Jason-LI2020
